---
# Provision the Common Development Environment (CDE)

- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    HOME_DIR: "/home/{{ansible_env.SUDO_USER}}"

  tasks:
    - include: tasks/linux/install-packages.yml
